name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/reusable-base.yml
    with:
      yarn-test-script: lint

  check-types:
    uses: ./.github/workflows/reusable-base.yml
    with:
      yarn-test-script: check-types

  playwright-test:
    uses: ./.github/workflows/reusable-base.yml
    with:
      build-script: npx playwright install chromium
      yarn-test-script: playwright:ci
      upload-path: playwright-report/

  unit-test:
    uses: ./.github/workflows/reusable-base.yml
    with:
      yarn-test-script: test
